/home/ubuntu/.local/lib/python3.8/site-packages/FinanceDataReader/wikipedia/listing.py:13: FutureWarning:

The default value of regex will change from True to False in a future version.

  0%|          | 0/4052 [00:00<?, ?it/s]  6%|▌         | 240/4052 [00:00<00:02, 1813.64it/s] 12%|█▏        | 480/4052 [00:00<00:02, 1680.42it/s] 16%|█▋        | 660/4052 [00:00<00:02, 1545.05it/s] 21%|██        | 840/4052 [00:00<00:02, 1458.40it/s] 25%|██▌       | 1020/4052 [00:00<00:02, 1358.76it/s] 30%|██▉       | 1200/4052 [00:00<00:02, 1278.55it/s] 34%|███▍      | 1380/4052 [00:01<00:02, 1199.42it/s] 38%|███▊      | 1560/4052 [00:01<00:02, 1128.70it/s] 41%|████▏     | 1680/4052 [00:01<00:02, 1102.49it/s] 44%|████▍     | 1800/4052 [00:01<00:02, 1054.15it/s] 47%|████▋     | 1920/4052 [00:01<00:02, 1007.86it/s] 50%|█████     | 2040/4052 [00:01<00:02, 972.18it/s]  53%|█████▎    | 2160/4052 [00:01<00:02, 934.07it/s] 56%|█████▋    | 2280/4052 [00:02<00:01, 898.31it/s] 59%|█████▉    | 2400/4052 [00:02<00:01, 866.42it/s] 62%|██████▏   | 2520/4052 [00:02<00:01, 833.63it/s] 65%|██████▌   | 2640/4052 [00:02<00:01, 709.83it/s] 68%|██████▊   | 2760/4052 [00:02<00:01, 714.42it/s] 71%|███████   | 2880/4052 [00:02<00:01, 717.71it/s] 74%|███████▍  | 3000/4052 [00:03<00:01, 712.77it/s] 77%|███████▋  | 3120/4052 [00:03<00:01, 697.38it/s] 80%|███████▉  | 3240/4052 [00:03<00:01, 683.75it/s] 83%|████████▎ | 3360/4052 [00:03<00:01, 674.66it/s] 86%|████████▌ | 3480/4052 [00:03<00:00, 657.15it/s] 89%|████████▉ | 3600/4052 [00:03<00:00, 641.37it/s] 92%|█████████▏| 3720/4052 [00:04<00:00, 621.23it/s] 95%|█████████▍| 3840/4052 [00:04<00:00, 610.98it/s] 98%|█████████▊| 3960/4052 [00:04<00:00, 594.75it/s] 99%|█████████▉| 4020/4052 [00:04<00:00, 589.96it/s]100%|██████████| 4052/4052 [00:04<00:00, 824.43it/s]
  0%|          | 0/3319 [00:00<?, ?it/s]  5%|▌         | 180/3319 [00:00<00:01, 1763.15it/s] 11%|█         | 360/3319 [00:00<00:01, 1647.74it/s] 16%|█▋        | 540/3319 [00:00<00:01, 1573.67it/s] 22%|██▏       | 720/3319 [00:00<00:01, 1511.57it/s] 27%|██▋       | 900/3319 [00:00<00:01, 1444.11it/s] 33%|███▎      | 1080/3319 [00:00<00:01, 1375.20it/s] 38%|███▊      | 1260/3319 [00:00<00:01, 1292.35it/s] 43%|████▎     | 1440/3319 [00:01<00:01, 1200.37it/s] 49%|████▉     | 1620/3319 [00:01<00:01, 1123.57it/s] 52%|█████▏    | 1740/3319 [00:01<00:01, 1086.22it/s] 56%|█████▌    | 1860/3319 [00:01<00:01, 1030.80it/s] 60%|█████▉    | 1980/3319 [00:01<00:01, 986.07it/s]  63%|██████▎   | 2100/3319 [00:01<00:01, 949.66it/s] 67%|██████▋   | 2220/3319 [00:01<00:01, 910.01it/s] 71%|███████   | 2340/3319 [00:02<00:01, 853.91it/s] 74%|███████▍  | 2460/3319 [00:02<00:01, 831.71it/s] 78%|███████▊  | 2580/3319 [00:02<00:00, 803.84it/s] 81%|████████▏ | 2700/3319 [00:02<00:00, 778.01it/s] 85%|████████▍ | 2820/3319 [00:02<00:00, 766.28it/s] 89%|████████▊ | 2940/3319 [00:02<00:00, 743.36it/s] 92%|█████████▏| 3060/3319 [00:03<00:00, 720.67it/s] 96%|█████████▌| 3180/3319 [00:03<00:00, 699.36it/s] 99%|█████████▉| 3300/3319 [00:03<00:00, 682.92it/s]100%|██████████| 3319/3319 [00:03<00:00, 915.17it/s]
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "HA_telBot7.py", line 375, in get_name
    txt1 = asyncio.run(aoaposition.get_klayPrice())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ubuntu/aoaposition.py", line 73, in get_klayPrice
    kspPrice = WebDriverWait(driver, 30).until(EC.presence_of_element_located((By.XPATH, "//*[@id='main-view']/section/article[1]/div[2]/section[3]/div[1]/dl[1]/dd/span[2]")))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "HA_telBot7.py", line 380, in get_name
    telbot.send_message(text=txt,  chat_id=chat_id, reply_markup=ReplyKeyboardRemove())
UnboundLocalError: local variable 'txt' referenced before assignment
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "HA_telBot7.py", line 375, in get_name
    txt1 = asyncio.run(aoaposition.get_klayPrice())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ubuntu/aoaposition.py", line 73, in get_klayPrice
    kspPrice = WebDriverWait(driver, 30).until(EC.presence_of_element_located((By.XPATH, "//*[@id='main-view']/section/article[1]/div[2]/section[3]/div[1]/dl[1]/dd/span[2]")))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "HA_telBot7.py", line 375, in get_name
    txt1 = asyncio.run(aoaposition.get_klayPrice())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ubuntu/aoaposition.py", line 73, in get_klayPrice
    kspPrice = WebDriverWait(driver, 30).until(EC.presence_of_element_located((By.XPATH, "//*[@id='main-view']/section/article[1]/div[2]/section[3]/div[1]/dl[1]/dd/span[2]")))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

